const CONFIG = {
  STORE_NAME: 'Sasi Arts & Photo Frames',
  STORE_TAGLINE: 'Create Memories Through Personalized Gifts',
  STORE_ADDRESS: 'Rajanagaram, Rajahmundry',
  WHATSAPP_NUMBER: '918106545049',
  WHATSAPP_LINK: 'https://wa.me/918106545049',
  WORKING_HOURS: 'Mon-Sat: 9:00 AM - 8:00 PM',
  GOOGLE_RATING: '4.8',
  PRIMARY_COLOR: '#FF6B00',
  SECONDARY_COLOR: '#D4AF37',
  DARK_COLOR: '#1A1A2E',
  LIGHT_COLOR: '#FFFFFF',
  SUPABASE_URL: 'https://wbjgiizrfdjhrccgsdbd.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiamdpaXpyZmRqaHJjY2dzZGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1NTY2NTMsImV4cCI6MjA5NzEzMjY1M30.SUVAmTBDvdo4pfGFOWQlMNxOOndgRnTH8N06t0xYbbg',

  RAZORPAY_KEY_ID: 'rzp_live_T3ue2C0zo4i9Tl',
  SITE_URL: 'https://sasiarts.in',
  CURRENCY: '₹',
  FREE_SHIPPING_ABOVE: 499,
  SHIPPING_CHARGE: 50,
  TAX_AMOUNT: 23.33,
  DELIVERY_ESTIMATE: '3-5 business days',
  BASE_LOCATION: 'Rajanagaram',
  BASE_PINCODE: 533294,
  API_BASE_URL: 'https://sasi-arts.vercel.app', // Change to your actual domain
  DELHIVERY_API_URL: 'https://track.delhivery.com',
  // ADMIN_PASSWORD_HASH removed — Supabase Auth handles login
  ADMIN_EMAIL: 'sodasanisasi387@gmail.com',
  // EmailJS config for invoice emails (sign up free at https://www.emailjs.com)
  EMAILJS_SERVICE_ID: 'service_cymxxes',
  EMAILJS_TEMPLATE_ID: 'template_xmrwntr',
  EMAILJS_PUBLIC_KEY: 'Yc62YDY3NxLyeoonN',
  PRODUCT_CATEGORIES: [
    'Personalized Photo Frames',
    'LED Photo Frames',
    'Acrylic Gifts',
    'Moon Lamps',
    'Magic Mirrors',
    'Photo Mugs',
    'Cushions',
    'Photo Clocks',
    'Crystal Gifts',
    'Keychains',
    'Name Plates',
    'Corporate Gifts',
    'Birthday Gifts',
    'Anniversary Gifts',
    'Wedding Gifts',
    'Bangles',
    'Sketch Art',
    'Blood Art'
  ]
};
